# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/hoofmeasurementwidget.ui'
#
# Created: Wed Jun 24 12:07:59 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_HoofMeasurementWidget(object):
    def setupUi(self, HoofMeasurementWidget):
        HoofMeasurementWidget.setObjectName("HoofMeasurementWidget")
        HoofMeasurementWidget.resize(884, 640)
        self.horizontalLayout = QtGui.QHBoxLayout(HoofMeasurementWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(HoofMeasurementWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.pageFile = QtGui.QWidget()
        self.pageFile.setGeometry(QtCore.QRect(0, 0, 200, 510))
        self.pageFile.setObjectName("pageFile")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageFile)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonSave = QtGui.QPushButton(self.pageFile)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_4.addWidget(self.pushButtonSave)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonLoad = QtGui.QPushButton(self.pageFile)
        self.pushButtonLoad.setEnabled(False)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_5.addWidget(self.pushButtonLoad)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(20, 146, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonDone = QtGui.QPushButton(self.pageFile)
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.horizontalLayout_3.addWidget(self.pushButtonDone)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.toolBox.addItem(self.pageFile, "")
        self.pageView = QtGui.QWidget()
        self.pageView.setGeometry(QtCore.QRect(0, 0, 200, 510))
        self.pageView.setObjectName("pageView")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pageView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonViewAll = QtGui.QPushButton(self.pageView)
        self.pushButtonViewAll.setObjectName("pushButtonViewAll")
        self.horizontalLayout_2.addWidget(self.pushButtonViewAll)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonHideAll = QtGui.QPushButton(self.pageView)
        self.pushButtonHideAll.setEnabled(False)
        self.pushButtonHideAll.setObjectName("pushButtonHideAll")
        self.horizontalLayout_6.addWidget(self.pushButtonHideAll)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.listWidget = QtGui.QListWidget(self.pageView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        spacerItem7 = QtGui.QSpacerItem(20, 238, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.toolBox.addItem(self.pageView, "")
        self.pageSegmentation = QtGui.QWidget()
        self.pageSegmentation.setGeometry(QtCore.QRect(0, 0, 200, 510))
        self.pageSegmentation.setObjectName("pageSegmentation")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pageSegmentation)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(self.pageSegmentation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.spinBoxPointSize = QtGui.QSpinBox(self.groupBox)
        self.spinBoxPointSize.setMinimum(1)
        self.spinBoxPointSize.setObjectName("spinBoxPointSize")
        self.horizontalLayout_9.addWidget(self.spinBoxPointSize)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonDeleteNode = QtGui.QPushButton(self.groupBox)
        self.pushButtonDeleteNode.setObjectName("pushButtonDeleteNode")
        self.horizontalLayout_8.addWidget(self.pushButtonDeleteNode)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.pageSegmentation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelAngle = QtGui.QLabel(self.groupBox_2)
        self.labelAngle.setObjectName("labelAngle")
        self.verticalLayout_6.addWidget(self.labelAngle)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditAngle = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditAngle.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditAngle.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEditAngle.setObjectName("lineEditAngle")
        self.horizontalLayout_7.addWidget(self.lineEditAngle)
        self.horizontalSliderAngle = QtGui.QSlider(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSliderAngle.sizePolicy().hasHeightForWidth())
        self.horizontalSliderAngle.setSizePolicy(sizePolicy)
        self.horizontalSliderAngle.setMaximum(100)
        self.horizontalSliderAngle.setProperty("value", 50)
        self.horizontalSliderAngle.setSliderPosition(50)
        self.horizontalSliderAngle.setTracking(False)
        self.horizontalSliderAngle.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAngle.setObjectName("horizontalSliderAngle")
        self.horizontalLayout_7.addWidget(self.horizontalSliderAngle)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.toolBox.addItem(self.pageSegmentation, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.widgetZinc = ZincHoofMeasurementWidget(HoofMeasurementWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetZinc.sizePolicy().hasHeightForWidth())
        self.widgetZinc.setSizePolicy(sizePolicy)
        self.widgetZinc.setObjectName("widgetZinc")
        self.horizontalLayout.addWidget(self.widgetZinc)

        self.retranslateUi(HoofMeasurementWidget)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(HoofMeasurementWidget)

    def retranslateUi(self, HoofMeasurementWidget):
        HoofMeasurementWidget.setWindowTitle(QtGui.QApplication.translate("HoofMeasurementWidget", "Hoof Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("HoofMeasurementWidget", "&Hoof Measurment Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoad.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDone.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageFile), QtGui.QApplication.translate("HoofMeasurementWidget", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonViewAll.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHideAll.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "Hide All", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageView), QtGui.QApplication.translate("HoofMeasurementWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("HoofMeasurementWidget", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeleteNode.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("HoofMeasurementWidget", "Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAngle.setText(QtGui.QApplication.translate("HoofMeasurementWidget", "Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageSegmentation), QtGui.QApplication.translate("HoofMeasurementWidget", "Segmentation", None, QtGui.QApplication.UnicodeUTF8))

from zinchoofmeasurementwidget import ZincHoofMeasurementWidget
